language: ruby

before_install:
  - gem install bundler -v '<2'

rvm:
  - 2.3
  - 2.6

env: CI="travis"

notifications:
  email: false
  flowdock: 1da4416b8ff98d1880986472428b1b1b

branches:
  only:
    - master
    - 5.0-dev
